[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "forecast>=0.1.0",
    "mysql-connector-python>=9.3.0",
    "pandas>=2.3.1",
    "prophet>=1.1.7",
]
